CC = g++

GLLIBS =  -lalleg  -I/home/monstruosoft/libs/usr/local/include/ -L/home/monstruosoft/libs/usr/local/lib/ -lallegro -lallegro_primitives -lallegro_image 

all: greedy_firefighter.cpp 
	$(CC) greedy_firefighter.cpp  -o greedy_firefighter $(GLLIBS) 

clean:
	rm -f greedy_firefighter
